#para portas, pwm, adc
CONFIG_GPIO=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_PWM=y
CONFIG_SERIAL=y
CONFIG_ADC=y

#valor para evitar stack overflow em alguns exemplos 2048
CONFIG_MAIN_STACK_SIZE=2048

#para o shell
CONFIG_SHELL=y
CONFIG_SHELL_CMDS=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_HISTORY=y

#habilita explicitamente o console via UART
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y

# Para listar threads
CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y

# Para métricas de tempo de execução
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y

# Para sys_heap mostrar informações
CONFIG_NEWLIB_LIBC=y
#valor comum em exemplos 4096
CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_SHELL_BACKEND_SERIAL=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=2048