# Configuração do Kernel
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Drivers de GPIO
CONFIG_GPIO=y

# Drivers de UART
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL=y

# Drivers de ADC
CONFIG_ADC=y

# Drivers de I2C (para o display)
CONFIG_I2C=y

# Drivers de Display
CONFIG_DISPLAY=y

# Configurações de Console e Logging
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_EARLY_CONSOLE=y

# Threads
CONFIG_NUM_PREEMPT_PRIORITIES=10

# Heap
CONFIG_SYS_HEAP_RUNTIME_STATS=y

# STM32 específico
CONFIG_CLOCK_CONTROL=y
CONFIG_PINCTRL=y